package nts.uk.file.at.app.export.vacation.set;

public enum EmployeeSystem {
    SETTING_PRIORITY,
    ANNUAL_HOLIDAYS,
    CROWDED_COMPANY,
    STEADY_EMPLOYMENT,
    OFFTIME_COMPANY,
    SUBSTITUTE_EMPLOYMENT,
    SHUTDOWM_COMPANY,
    PAID_WORK,
    NURSING_CARE,
    SIXTY_HOURS,
    SPECIAL_LEAVE_SETTING
}
