DECLARE @CONTRACT_CD CHAR(12) = '000000000000';

INSERT INTO UK_CNVERT_WORK.dbo.SCVMT_MAPPING_CODE_TO_CID(âÔé–CD, CID, CCD) ( SELECT âÔé–CD, CONCAT('000000000000-',RIGHT(CONCAT('0000',âÔé–CD),4)), RIGHT(CONCAT('0000',âÔé–CD),4) FROM ERP.dbo.kyotukaisya_m);

CREATE TABLE #SCVMT_MAPPING_PARENT(
CATEGORY_NAME VARCHAR(50) NOT NULL,
PARENT_TBL_NAME VARCHAR(50) NOT NULL,
TARGET_COLUMN_NAME VARCHAR(50) NOT NULL,
SOURCE_PK1 VARCHAR(30) NOT NULL,
SOURCE_PK2 VARCHAR(30) NOT NULL,
SOURCE_PK3 VARCHAR(30) NOT NULL,
SOURCE_PK4 VARCHAR(30) NOT NULL,
SOURCE_PK5 VARCHAR(30) NOT NULL,
SOURCE_PK6 VARCHAR(30) NOT NULL,
SOURCE_PK7 VARCHAR(30) NOT NULL,
SOURCE_PK8 VARCHAR(30) NOT NULL,
SOURCE_PK9 VARCHAR(30) NOT NULL,
SOURCE_PK10 VARCHAR(30) NOT NULL,
PARENT_VALUE VARCHAR(50) NOT NULL,
CONSTRAINT SCVMP_MAPPING_PARENT PRIMARY KEY CLUSTERED (CATEGORY_NAME,PARENT_TBL_NAME,TARGET_COLUMN_NAME,SOURCE_PK1,SOURCE_PK2,SOURCE_PK3,SOURCE_PK4,SOURCE_PK5,SOURCE_PK6,SOURCE_PK7,SOURCE_PK8,SOURCE_PK9,SOURCE_PK10)
);

INSERT INTO UK_WORK.dbo.SACMT_USER (
    ASSO_PID,
    CONTRACT_CD,
    DEFAULT_USER,
    EXPIRATION_DATE,
    LOGIN_ID,
    MAIL_ADD,
    MULTI_COM,
    PASSWORD,
    SPECIAL_USER,
    USER_ID,
    USER_NAME
)
(
 SELECT 
    base.kojin_id,
    @CONTRACT_CD,
    0,
    '9999-12-31',
    CONCAT(base.âÔé–CD,base.ã§í ÉçÉOÉCÉìCD),
    base.j_mail,
    0,
    pass.PASSWORD,
    0,
    NEWID(),
    base.é–àıñº
 FROM ERP.dbo.jm_kihon AS base
 INNER JOIN UK_CNVERT_WORK.dbo.SCVMT_MAPPING_PASSWORD AS pass
 ON base.web_passwd = pass.kojin_id
);


IF OBJECT_ID(N'tempdb..#SCVMT_MAPPING_PARENT', N'U') IS NOT NULL
DROP TABLE #SCVMT_MAPPING_PARENT;
