USE [master]
GO

IF EXISTS(SELECT * FROM sys.databases WHERE [name] = 'UK_CNVERT_WORK')
BEGIN
	ALTER DATABASE [UK_CNVERT_WORK] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE [UK_CNVERT_WORK]
END
GO

CREATE DATABASE [UK_CNVERT_WORK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UK_CNVERT_WORK', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER2016\MSSQL\DATA\UK_CNVERT_WORK.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UK_CNVERT_WORK_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER2016\MSSQL\DATA\UK_CNVERT_WORK_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UK_CNVERT_WORK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UK_CNVERT_WORK] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET ARITHABORT OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET  MULTI_USER 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UK_CNVERT_WORK] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UK_CNVERT_WORK] SET QUERY_STORE = OFF
GO

USE [UK_CNVERT_WORK]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [UK_CNVERT_WORK] SET  READ_WRITE 
GO

CREATE TABLE SCVMT_MAPPING_CODE_TO_CID(
	CID char(36) NOT NULL,
	CCD char(17) NOT NULL,
	‰ïŽÐCD decimal(2,0),
 CONSTRAINT SCVMP_MAPPING_CODE_TO_CID PRIMARY KEY CLUSTERED 
(
	CID
)
);

CREATE TABLE SCVMT_MAPPING_CODE_TO_CODE(
	MAPPING_TYPE nvarchar(50) NOT NULL,
	IN_VALUE nvarchar(50) NOT NULL,
	OUT_VALUE nvarchar(50) NOT NULL,
 CONSTRAINT SCVMP_MAPPING_CODE_TO_CODE PRIMARY KEY CLUSTERED 
(
	MAPPING_TYPE,
	IN_VALUE
)
);

CREATE TABLE SCVMT_MAPPING_PASSWORD(
	kojin_id int NOT NULL,
	‰ïŽÐCD decimal(2,0) NOT NULL,
	ŽÐˆõCD char(8) NOT NULL,
	USER_ID char(36) NOT NULL,
	PASSWORD char(66) NOT NULL,
 CONSTRAINT SCVMP_MAPPING_PASSWORD PRIMARY KEY CLUSTERED 
(
	kojin_id,
	‰ïŽÐCD,
	ŽÐˆõCD
)
);

CREATE TABLE SCVMT_MAPPING_FILE_ID(
	FILE_ID char(36) NOT NULL,
	FILE_TYPE varchar(25) NOT NULL,
	kojin_id int NULL,
	‰ïŽÐCD decimal(2,0) NULL,
	ŽÐˆõCD char(8) NULL,
 CONSTRAINT SCVMP_MAPPING_FILE_ID PRIMARY KEY CLUSTERED 
(
	FILE_ID
)
);

