start gradle_eclipse_one "nts.uk\pr"
start gradle_eclipse_one "nts.uk\pr\file"
start gradle_eclipse_one "nts.uk\pr\file\nts.uk.pr.file.infra"
start gradle_eclipse_one "nts.uk\pr\file\nts.uk.pr.file.ws"
start gradle_eclipse_one "nts.uk\pr\nts.uk.pr.web"
start gradle_eclipse_one "nts.uk\pr\proto"
start gradle_eclipse_one "nts.uk\pr\proto\nts.uk.pr.proto.app"
start gradle_eclipse_one "nts.uk\pr\proto\nts.uk.pr.proto.dom"
start gradle_eclipse_one "nts.uk\pr\proto\nts.uk.pr.proto.infra"
start gradle_eclipse_one "nts.uk\pr\proto\nts.uk.pr.proto.ws"
start gradle_eclipse_one "nts.uk\pr\screen"
start gradle_eclipse_one "nts.uk\pr\screen\nts.uk.pr.screen.app"
start gradle_eclipse_one "nts.uk\pr\screen\nts.uk.pr.screen.infra"
start gradle_eclipse_one "nts.uk\pr\screen\nts.uk.pr.screen.ws"

