package nts.uk.ctx.at.record.app.find.divergence.time;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum ScreenUseAtr {


	PERSONNELEXPENSES(0),

	DIVERGENCETIME(1),
	
	OVERTIME(2),
	
	ENTRYDIVERGENCETIME(3),
	
	EVACUATIONDEPARTURETIMR(4),

	PCLOGONDIVERGENCETIME(5),
	
	PCLOGOFFDIVERGENCETIME(6),
	
	PREDETERMINEDBREAKTIMEDIVERGENCE(7),
	
	NONSCHEDULEDDIVERGENCETIME(8),
	
	PREMATUREOVERTIMEDEPARTURETIME(9),
	
	NORMALOVERTIMEDEVIATIONTIME(10),
	
	HOLIDAYSDEPARTURETIME(11),
	
	ARBITRARYDIVERGENCETIME(12),	
	
	ATTENDANCETYPEOFDERVICETYPE(13),
		
	EMPLOYEEBOOKINGHOURS(14),
	
	TIMEOFCUMULATIVEARRIVAL(15),	
	
	WORKTIME(16),	
	
	ATTENDANCETIMES(17),	
	
	TOTALCOMMUTINGAMOUNT(18),	
	
	DAILYWORKSCHEDULE(19);
	
	public final int value;
}
