package nts.uk.ctx.at.record.dom.monthly.mergetable;

import lombok.Getter;
import lombok.Setter;
import nts.uk.ctx.at.record.dom.monthly.excessoutside.ExcessOutsideWorkOfMonthly;
@Getter
@Setter
public class ExcessOutsideWorkOfMonthlyMerge {
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly1;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly2;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly3;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly4;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly5;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly6;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly7;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly8;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly9;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly10;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly11;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly12;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly13;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly14;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly15;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly16;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly17;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly18;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly19;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly20;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly21;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly22;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly23;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly24;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly25;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly26;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly27;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly28;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly29;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly30;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly31;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly32;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly33;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly34;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly35;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly36;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly37;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly38;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly39;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly40;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly41;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly42;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly43;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly44;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly45;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly46;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly47;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly48;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly49;
	ExcessOutsideWorkOfMonthly	excessOutsideWorkOfMonthly50;

}
