package nts.uk.ctx.at.record.dom.monthly.mergetable;

import lombok.Getter;
import lombok.Setter;
import nts.uk.ctx.at.record.dom.monthly.vacation.specialholiday.monthremaindata.SpecialHolidayRemainData;
@Getter
@Setter
public class SpecialHolidayRemainDataMerge {
	SpecialHolidayRemainData specialHolidayRemainData1;
	SpecialHolidayRemainData specialHolidayRemainData2;
	SpecialHolidayRemainData specialHolidayRemainData3;
	SpecialHolidayRemainData specialHolidayRemainData4;
	SpecialHolidayRemainData specialHolidayRemainData5;
	SpecialHolidayRemainData specialHolidayRemainData6;
	SpecialHolidayRemainData specialHolidayRemainData7;
	SpecialHolidayRemainData specialHolidayRemainData8;
	SpecialHolidayRemainData specialHolidayRemainData9;
	SpecialHolidayRemainData specialHolidayRemainData10;
	SpecialHolidayRemainData specialHolidayRemainData11;
	SpecialHolidayRemainData specialHolidayRemainData12;
	SpecialHolidayRemainData specialHolidayRemainData13;
	SpecialHolidayRemainData specialHolidayRemainData14;
	SpecialHolidayRemainData specialHolidayRemainData15;
	SpecialHolidayRemainData specialHolidayRemainData16;
	SpecialHolidayRemainData specialHolidayRemainData17;
	SpecialHolidayRemainData specialHolidayRemainData18;
	SpecialHolidayRemainData specialHolidayRemainData19;
	SpecialHolidayRemainData specialHolidayRemainData20;

}
