package nts.uk.ctx.hr.shared.dom.personalinfo.perinfo.perinfohr.personalInfo;

import java.util.List;
import java.util.stream.Collectors;

import javax.inject.Inject;

import nts.uk.ctx.hr.shared.dom.personalinfo.perinfo.PersonalInformation;
import nts.uk.ctx.hr.shared.dom.personalinfo.perinfo.PersonalInformationRepository;

/**
 * UKDesign.ドメインモデル.NittsuSystem.UniversalK.人事.shared.個人情報（人事）.個人情報.アルゴリズム.個人情報（人事）(Thông tin cá nhân (Nhân sự).個人情報の追加 (Thêm thông tin cá nhân)).個人情報の追加
 * @author chungnt
 *
 */

public class AddPersonInfoHR {

	@Inject
	private PersonalInformationRepository repo;
	
	public void add(List<AddPersonInfoHRInput> personInfoHRInputs) {
		
		if (!personInfoHRInputs.isEmpty()) {
			List<PersonalInformation> perInfos =  personInfoHRInputs.stream().map(m -> {
//				PersonalInformation perInfoBuilder = PersonalInformation.builder()
//						.contractCd(m.getContractCd())
//						.histId(m.getHistId())
//						.build();
				PersonalInformation perInfo = new PersonalInformation(m.getContractCd(),
						m.getEndDate(),
						m.getHistId(),
						m.getPId(),
						m.getStartDate(),
						m.getWorkId(),
						m.getCompanyCode(),
						m.getCid(),
						m.getDate01(),
						m.getDate02(),
						m.getDate03(),
						m.getDate04(),
						m.getDate05(),
						m.getDate06(),
						m.getDate07(),
						m.getDate08(),
						m.getDate09(),
						m.getDate10(),
						m.getInt01(),
						m.getInt02(),
						m.getInt03(),
						m.getInt04(),
						m.getInt05(),
						m.getInt06(),
						m.getInt07(),
						m.getInt08(),
						m.getInt09(),
						m.getInt10(),
						m.getInt11(),
						m.getInt12(),
						m.getInt13(),
						m.getInt14(),
						m.getInt15(),
						m.getInt16(),
						m.getInt17(),
						m.getInt18(),
						m.getInt19(),
						m.getInt20(),
						m.getInt21(),
						m.getInt22(),
						m.getInt23(),
						m.getInt24(),
						m.getInt25(),
						m.getInt26(),
						m.getInt27(),
						m.getInt28(),
						m.getInt29(),
						m.getInt30(),
						m.getNumber01(),
						m.getNumber02(),
						m.getNumber03(),
						m.getNumber04(),
						m.getNumber05(),
						m.getNumber06(),
						m.getNumber07(),
						m.getNumber08(),
						m.getNumber09(),
						m.getNumber10(),
						m.getNumber11(),
						m.getNumber12(),
						m.getNumber13(),
						m.getNumber14(),
						m.getNumber15(),
						m.getNumber16(),
						m.getNumber17(),
						m.getNumber18(),
						m.getNumber19(),
						m.getNumber20(),
						m.getNumber21(),
						m.getNumber22(),
						m.getNumber23(),
						m.getNumber24(),
						m.getNumber25(),
						m.getNumber26(),
						m.getNumber27(),
						m.getNumber28(),
						m.getNumber29(),
						m.getNumber30(),
						m.getPersonName(),
						m.getReleaseDate(),
						m.getRequestFlg(),
						m.getRptLayoutId(),
						m.getRptNumber(),
						m.getRptId(),
						m.getScd(),
						m.getSelectCode01(),
						m.getSelectCode02(),
						m.getSelectCode03(),
						m.getSelectCode04(),
						m.getSelectCode05(),
						m.getSelectCode06(),
						m.getSelectCode07(),
						m.getSelectCode08(),
						m.getSelectCode09(),
						m.getSelectCode10(),
						m.getSelectCode11(),
						m.getSelectCode12(),
						m.getSelectCode13(),
						m.getSelectCode14(),
						m.getSelectCode15(),
						m.getSelectCode16(),
						m.getSelectCode17(),
						m.getSelectCode18(),
						m.getSelectCode19(),
						m.getSelectCode20(),
						m.getSelectId01(),
						m.getSelectId02(),
						m.getSelectId03(),
						m.getSelectId04(),
						m.getSelectId05(),
						m.getSelectId06(),
						m.getSelectId07(),
						m.getSelectId08(),
						m.getSelectId09(),
						m.getSelectId10(),
						m.getSelectId11(),
						m.getSelectId12(),
						m.getSelectId13(),
						m.getSelectId14(),
						m.getSelectId15(),
						m.getSelectId16(),
						m.getSelectId17(),
						m.getSelectId18(),
						m.getSelectId19(),
						m.getSelectId20(),
						m.getSelectName01(),
						m.getSelectName02(),
						m.getSelectName03(),
						m.getSelectName04(),
						m.getSelectName05(),
						m.getSelectName06(),
						m.getSelectName07(),
						m.getSelectName08(),
						m.getSelectName09(),
						m.getSelectName10(),
						m.getSelectName11(),
						m.getSelectName12(),
						m.getSelectName13(),
						m.getSelectName14(),
						m.getSelectName15(),
						m.getSelectName16(),
						m.getSelectName17(),
						m.getSelectName18(),
						m.getSelectName19(),
						m.getSelectName20(),
						m.getSid(),
						m.getStr01(),
						m.getStr02(),
						m.getStr03(),
						m.getStr04(),
						m.getStr05(),
						m.getStr06(),
						m.getStr07(),
						m.getStr08(),
						m.getStr09(),
						m.getStr10(),
						m.getStr11(),
						m.getStr12(),
						m.getStr13(),
						m.getStr14(),
						m.getStr15(),
						m.getStr16(),
						m.getStr17(),
						m.getStr18(),
						m.getStr19(),
						m.getStr20(),
						m.getStr21(),
						m.getStr22(),
						m.getStr23(),
						m.getStr24(),
						m.getStr25(),
						m.getStr26(),
						m.getStr27(),
						m.getStr28(),
						m.getStr29(),
						m.getStr20(),
						m.getStr31(),
						m.getStr32(),
						m.getStr33(),
						m.getStr34(),
						m.getStr35(),
						m.getStr36(),
						m.getStr37(),
						m.getStr38(),
						m.getStr39(),
						m.getStr30(),
						m.getStr41(),
						m.getStr42(),
						m.getStr43(),
						m.getStr44(),
						m.getStr45(),
						m.getStr46(),
						m.getStr47(),
						m.getStr48(),
						m.getStr49(),
						m.getStr40(),
						m.getStr51(),
						m.getStr52(),
						m.getStr53(),
						m.getStr54(),
						m.getStr55(),
						m.getStr56(),
						m.getStr57(),
						m.getStr58(),
						m.getStr59(),
						m.getStr60(),
						m.getWorkName());
				return perInfo;
			}).collect(Collectors.toList());
			
			for (PersonalInformation personalInformation : perInfos) {
				repo.insert(personalInformation);
			}
		}
	}
}