package nts.uk.ctx.hr.shared.dom.personalinfo.perinfo.perinfohr.personalInfo;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import javax.ejb.Stateless;
import javax.inject.Inject;

import nts.uk.ctx.hr.shared.dom.personalinfo.perinfo.PersonalInformation;
import nts.uk.ctx.hr.shared.dom.personalinfo.perinfo.PersonalInformationRepository;

/**
 * UKDesign.ドメインモデル.NittsuSystem.UniversalK.人事.shared.個人情報（人事）.個人情報.アルゴリズム.個人情報（人事）(Thông tin cá nhân (Nhân sự).個人情報の更新 (cập nhật thông tin cá nhân).個人情報の更新
 * @author chungnt
 *
 */

@Stateless
public class UpdatePersonInfoHR {
	
	@Inject
	private PersonalInformationRepository repo;

	public void update(List<UpdatePersonInfoHRInput> personInfoHRInputs) {
		
		if (!personInfoHRInputs.isEmpty()) {
			List<PersonalInformation> perInfos =  personInfoHRInputs.stream().map(m -> {
				PersonalInformation perInfo = new PersonalInformation(
						m.getContractCd(),
						m.getEndDate(),
						m.getHistId(),
						m.getPId(),
						m.getStartDate(),
						m.getWorkId(),
						Optional.ofNullable(m.getCompanyCode()),
						Optional.ofNullable(m.getCid()),
						Optional.ofNullable(m.getDate01()),
						Optional.ofNullable(m.getDate02()),
						Optional.ofNullable(m.getDate03()),
						Optional.ofNullable(m.getDate04()),
						Optional.ofNullable(m.getDate05()),
						Optional.ofNullable(m.getDate06()),
						Optional.ofNullable(m.getDate07()),
						Optional.ofNullable(m.getDate08()),
						Optional.ofNullable(m.getDate09()),
						Optional.ofNullable(m.getDate10()),
						m.getInt01(),
						m.getInt02(),
						m.getInt03(),
						m.getInt04(),
						m.getInt05(),
						m.getInt06(),
						m.getInt07(),
						m.getInt08(),
						m.getInt09(),
						m.getInt10(),
						m.getInt11(),
						m.getInt12(),
						m.getInt13(),
						m.getInt14(),
						m.getInt15(),
						m.getInt16(),
						m.getInt17(),
						m.getInt18(),
						m.getInt19(),
						m.getInt20(),
						m.getInt21(),
						m.getInt22(),
						m.getInt23(),
						m.getInt24(),
						m.getInt25(),
						m.getInt26(),
						m.getInt27(),
						m.getInt28(),
						m.getInt29(),
						m.getInt30(),
						m.getNumber01(),
						m.getNumber02(),
						m.getNumber03(),
						m.getNumber04(),
						m.getNumber05(),
						m.getNumber06(),
						m.getNumber07(),
						m.getNumber08(),
						m.getNumber09(),
						m.getNumber10(),
						m.getNumber11(),
						m.getNumber12(),
						m.getNumber13(),
						m.getNumber14(),
						m.getNumber15(),
						m.getNumber16(),
						m.getNumber17(),
						m.getNumber18(),
						m.getNumber19(),
						m.getNumber20(),
						m.getNumber21(),
						m.getNumber22(),
						m.getNumber23(),
						m.getNumber24(),
						m.getNumber25(),
						m.getNumber26(),
						m.getNumber27(),
						m.getNumber28(),
						m.getNumber29(),
						m.getNumber30(),
						Optional.ofNullable(m.getPersonName()),
						Optional.ofNullable(m.getReleaseDate()),
						m.getRequestFlg(),
						m.getRptLayoutId(),
						Optional.ofNullable(m.getRptNumber()),
						Optional.ofNullable(m.getRptId()), 
						Optional.ofNullable(m.getScd()),
						Optional.ofNullable(m.getSelectCode01()),
						Optional.ofNullable(m.getSelectCode02()),
						Optional.ofNullable(m.getSelectCode03()),
						Optional.ofNullable(m.getSelectCode04()),
						Optional.ofNullable(m.getSelectCode05()),
						Optional.ofNullable(m.getSelectCode06()),
						Optional.ofNullable(m.getSelectCode07()),
						Optional.ofNullable(m.getSelectCode08()),
						Optional.ofNullable(m.getSelectCode09()),
						Optional.ofNullable(m.getSelectCode10()),
						Optional.ofNullable(m.getSelectCode11()),
						Optional.ofNullable(m.getSelectCode12()),
						Optional.ofNullable(m.getSelectCode13()),
						Optional.ofNullable(m.getSelectCode14()),
						Optional.ofNullable(m.getSelectCode15()),
						Optional.ofNullable(m.getSelectCode16()),
						Optional.ofNullable(m.getSelectCode17()),
						Optional.ofNullable(m.getSelectCode18()),
						Optional.ofNullable(m.getSelectCode19()),
						Optional.ofNullable(m.getSelectCode20()),
						m.getSelectId01(),
						m.getSelectId02(),
						m.getSelectId03(),
						m.getSelectId04(),
						m.getSelectId05(),
						m.getSelectId06(),
						m.getSelectId07(),
						m.getSelectId08(),
						m.getSelectId09(),
						m.getSelectId10(),
						m.getSelectId11(),
						m.getSelectId12(),
						m.getSelectId13(),
						m.getSelectId14(),
						m.getSelectId15(),
						m.getSelectId16(),
						m.getSelectId17(),
						m.getSelectId18(),
						m.getSelectId19(),
						m.getSelectId20(),
						Optional.ofNullable(m.getSelectName01()),
						Optional.ofNullable(m.getSelectName02()),
						Optional.ofNullable(m.getSelectName03()),
						Optional.ofNullable(m.getSelectName04()),
						Optional.ofNullable(m.getSelectName05()),
						Optional.ofNullable(m.getSelectName06()),
						Optional.ofNullable(m.getSelectName07()),
						Optional.ofNullable(m.getSelectName08()),
						Optional.ofNullable(m.getSelectName09()),
						Optional.ofNullable(m.getSelectName10()),
						Optional.ofNullable(m.getSelectName11()),
						Optional.ofNullable(m.getSelectName12()),
						Optional.ofNullable(m.getSelectName13()),
						Optional.ofNullable(m.getSelectName14()),
						Optional.ofNullable(m.getSelectName15()),
						Optional.ofNullable(m.getSelectName16()),
						Optional.ofNullable(m.getSelectName17()),
						Optional.ofNullable(m.getSelectName18()),
						Optional.ofNullable(m.getSelectName19()),
						Optional.ofNullable(m.getSelectName20()),
						Optional.ofNullable(m.getSid()),
						Optional.ofNullable(m.getStr01()),
						Optional.ofNullable(m.getStr02()),
						Optional.ofNullable(m.getStr03()),
						Optional.ofNullable(m.getStr04()),
						Optional.ofNullable(m.getStr05()),
						Optional.ofNullable(m.getStr06()),
						Optional.ofNullable(m.getStr07()),
						Optional.ofNullable(m.getStr08()),
						Optional.ofNullable(m.getStr09()),
						Optional.ofNullable(m.getStr10()),
						Optional.ofNullable(m.getStr11()),
						Optional.ofNullable(m.getStr12()),
						Optional.ofNullable(m.getStr13()),
						Optional.ofNullable(m.getStr14()),
						Optional.ofNullable(m.getStr15()),
						Optional.ofNullable(m.getStr16()),
						Optional.ofNullable(m.getStr17()),
						Optional.ofNullable(m.getStr18()),
						Optional.ofNullable(m.getStr19()),
						Optional.ofNullable(m.getStr20()),
						Optional.ofNullable(m.getStr21()),
						Optional.ofNullable(m.getStr22()),
						Optional.ofNullable(m.getStr23()),
						Optional.ofNullable(m.getStr24()),
						Optional.ofNullable(m.getStr25()),
						Optional.ofNullable(m.getStr26()),
						Optional.ofNullable(m.getStr27()),
						Optional.ofNullable(m.getStr28()),
						Optional.ofNullable(m.getStr29()),
						Optional.ofNullable(m.getStr30()),
						Optional.ofNullable(m.getStr31()),
						Optional.ofNullable(m.getStr31()),
						Optional.ofNullable(m.getStr33()),
						Optional.ofNullable(m.getStr34()),
						Optional.ofNullable(m.getStr35()),
						Optional.ofNullable(m.getStr36()),
						Optional.ofNullable(m.getStr37()),
						Optional.ofNullable(m.getStr38()),
						Optional.ofNullable(m.getStr39()),
						Optional.ofNullable(m.getStr40()),
						Optional.ofNullable(m.getStr41()),
						Optional.ofNullable(m.getStr42()),
						Optional.ofNullable(m.getStr43()),
						Optional.ofNullable(m.getStr44()),
						Optional.ofNullable(m.getStr45()),
						Optional.ofNullable(m.getStr46()),
						Optional.ofNullable(m.getStr47()),
						Optional.ofNullable(m.getStr48()),
						Optional.ofNullable(m.getStr49()),
						Optional.ofNullable(m.getStr50()),
						Optional.ofNullable(m.getStr51()),
						Optional.ofNullable(m.getStr52()),
						Optional.ofNullable(m.getStr53()),
						Optional.ofNullable(m.getStr54()),
						Optional.ofNullable(m.getStr55()),
						Optional.ofNullable(m.getStr56()),
						Optional.ofNullable(m.getStr57()),
						Optional.ofNullable(m.getStr58()),
						Optional.ofNullable(m.getStr59()),
						Optional.ofNullable(m.getStr60()),
						Optional.ofNullable(m.getWorkName()));

				return perInfo;
			}).collect(Collectors.toList());
			
			for (PersonalInformation personalInformation : perInfos) {
				repo.update(personalInformation);
			}
		}
	}
	
}
