/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hoanld' at '10/19/16 1:27 PM' with Gradle 2.14.1
 *
 * @author hoanld, @date 10/19/16 1:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
