module nts.uk.pr.view.qmm003.share.constants {
    export const listRegions: Array<any> = [
        {code: "_1", name: "北海道"}, 
        {code: "_2", name: "東北"}, 
        {code: "_3", name: "関東"}, 
        {code: "_4", name: "中部"}, 
        {code: "_5", name: "近畿"}, 
        {code: "_6", name: "中国"}, 
        {code: "_7", name: "四国"}, 
        {code: "_8", name: "九州"}
    ];
    
    export const listPrefectures: Array<any> = [
        {code: 1, name: "北海道", region: "_1"},
        {code: 2, name: "青森県", region: "_2"},
        {code: 3, name: "岩手県", region: "_2"},
        {code: 4, name: "宮城県", region: "_2"},
        {code: 5, name: "秋田県", region: "_2"},
        {code: 6, name: "山形県", region: "_2"},
        {code: 7, name: "福島県", region: "_2"},
        {code: 8, name: "茨城県", region: "_3"},
        {code: 9, name: "栃木県", region: "_3"},
        {code: 10, name: "群馬県", region: "_3"},
        {code: 11, name: "埼玉県", region: "_3"},
        {code: 12, name: "千葉県", region: "_3"},
        {code: 13, name: "東京都", region: "_3"},
        {code: 14, name: "神奈川県", region: "_3"},
        {code: 15, name: "新潟県", region: "_4"},
        {code: 16, name: "富山県", region: "_4"},
        {code: 17, name: "石川県", region: "_4"},
        {code: 18, name: "福井県", region: "_4"},
        {code: 19, name: "山梨県", region: "_4"},
        {code: 20, name: "長野県", region: "_4"},
        {code: 21, name: "岐阜県", region: "_4"},
        {code: 22, name: "静岡県", region: "_4"},
        {code: 23, name: "愛知県", region: "_4"},
        {code: 24, name: "三重県", region: "_5"},
        {code: 25, name: "滋賀県", region: "_5"},
        {code: 26, name: "京都府", region: "_5"},
        {code: 27, name: "大阪府", region: "_5"},
        {code: 28, name: "兵庫県", region: "_5"},
        {code: 29, name: "奈良県", region: "_5"},
        {code: 30, name: "和歌山県", region: "_5"},
        {code: 31, name: "鳥取県", region: "_6"},
        {code: 32, name: "島根県", region: "_6"},
        {code: 33, name: "岡山県", region: "_6"},
        {code: 34, name: "広島県", region: "_6"},
        {code: 35, name: "山口県", region: "_6"},
        {code: 36, name: "徳島県", region: "_7"},
        {code: 37, name: "香川県", region: "_7"},
        {code: 38, name: "愛媛県", region: "_7"},
        {code: 39, name: "高知県", region: "_7"},
        {code: 40, name: "福岡県", region: "_8"},
        {code: 41, name: "佐賀県", region: "_8"},
        {code: 42, name: "長崎県", region: "_8"},
        {code: 43, name: "熊本県", region: "_8"},
        {code: 44, name: "大分県", region: "_8"},
        {code: 45, name: "宮崎県", region: "_8"},
        {code: 46, name: "鹿児島県", region: "_8"},
        {code: 47, name: "沖縄県", region: "_8"}
    ];
}