package nts.uk.file.at.app.export.setworkinghoursanddays;

public class EmploymentColumn {
	public static final String KMK004_185 = "雇用コード";
    public static final String KMK004_186 = "雇用名称";
    public static final String KMK004_372 = "年度";
    public static final String KMK004_373 = "通常勤務";
    public static final String KMK004_374 = "法定労働時間_Normal";
    public static final String KMK004_375 = "1日の法定労働時間_Normal";
    public static final String KMK004_376 = "1週の法定労働時間_Normal";
    public static final String KMK004_377 = "給与上で週割増・月割増時間を求めるか_Normal";
    public static final String KMK004_378 = "給与上での週割増・月割増の対象 法内残業_Normal";
    public static final String KMK004_379 = "給与上での週割増・月割増の対象 法外休出_Normal";
    public static final String KMK004_380 = "時間外・36協定の計算で週割増・月割増時間を求めるか_Normal";
    public static final String KMK004_381 = "時間外・36協定の計算での週割増・月割増の対象法内残業 法内残業_Normal";
    public static final String KMK004_382 = "時間外・36協定の計算での週割増・月割増の対象法内残業 法外休出_Normal";
    public static final String KMK004_383 = "フレックス勤務 所定労働時間";
    public static final String KMK004_384 = "フレックス勤務";
    public static final String KMK004_385 = "所定労働時間";
    public static final String KMK004_386 = "法定労働時間_Flex";
    public static final String KMK004_387 = "当月精算基準";
    public static final String KMK004_388 = "清算期間";
    public static final String KMK004_389 = "開始月";
    public static final String KMK004_390 = "期間_Flex";
    public static final String KMK004_391 = "不足時間の扱い";
    public static final String KMK004_392 = "月の集計方法";
    public static final String KMK004_393 = "残業時間をフレックス時間に含めるか";
    public static final String KMK004_394 = "法定外休出時間をフレックス時間に含めるか";
    public static final String KMK004_395 = "法定内フレックス集計設定";
    public static final String KMK004_396 = "変形労働";
    public static final String KMK004_397 = "法定労働時間_Defor";
    public static final String KMK004_375_1 = "1日の法定労働時間_Defor";
    public static final String KMK004_376_1 = "1週の法定労働時間_Defor";
    public static final String KMK004_398 = "期間設定開始月";
    public static final String KMK004_399 = "期間_Defor";
    public static final String KMK004_400 = "繰り返し";
    public static final String KMK004_377_1 = "給与上で週割増・月割増時間を求めるか_Defor";
    public static final String KMK004_378_1 = "給与上での週割増・月割増の対象 法内残業_Defor";
    public static final String KMK004_379_1 = "給与上での週割増・月割増の対象 法外休出_Defor";
    public static final String KMK004_380_1 = "時間外・36協定の計算で週割増・月割増時間を求めるか_Defor";
    public static final String KMK004_381_1 = "時間外・36協定の計算での週割増・月割増の対象法内残業 法内残業_Defor";
    public static final String KMK004_382_1 = "時間外・36協定の計算での週割増・月割増の対象法内残業 法外休出_Defor";
}
