package nts.uk.ctx.at.shared.dom.common;

/**
 * ２つの時間帯の位置関係
 * @author keisuke_hoshina
 *
 */
public enum RangeDuplication {

	SAME_SPAN,
	BASE_CONTAINS_COMPLETE,
	BASE_CONTAINS_SAME_START,
	BASE_CONTAINS_SAME_END,
	BASE_CONTAINED_COMPLETE,
	BASE_CONTAINED_SAME_START,
	BASE_CONTAINED_SAME_END,
	CONTINUOUS_AFTER_BASE,
	CONTINUOUS_BEFORE_BASE,
	BASE_BEFORE_COMPARED,
	BASE_AFTER_COMPARED,
	COMPARED_START_BETWEEN_BASE,
	COMPARED_END_BETWEEN_BASE
}
