package nts.uk.cnv.dom.td.alterationlog;

public enum AlterationType {
	TABLE_CREATE,
	TABLE_NAME_CHANGE,
	TABLE_JPNAME_CHANGE,
	PRIMARY_KEY_CHANGE,
	INDEX_CHANGE,
	TABLE_DROP,
	COLUMN_ADD,
	COLUMN_NAME_CHANGE,
	COLUMN_TYPE_CHANGE,
	COLUMN_JPNAME_CHANGE,
	COLUMN_COMMENT_CHANGE,
	COLUMN_CONTAINT_CHANGE,
	COLUMN_DEFAULT_VALUE_CHANGE,
	COLUMN_DELETE
}
