package nts.uk.file.at.infra.otpitem;

public class CalFormulasItemLang {
	public static final String GET_EXPORT_EXCEL_LANG;
	  static {
	      StringBuilder exportSQL = new StringBuilder();
	     exportSQL.append(" SELECT");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.OPTIONAL_ITEM_NO, NULL) AS OPTIONAL_ITEM_NO,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.OPTIONAL_ITEM_NAME, NULL) AS OPTIONAL_ITEM_NAME,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.OPTIONAL_ITEM_ATR, NULL) AS OPTIONAL_ITEM_ATR,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.UNIT_OF_OPTIONAL_ITEM, NULL) AS UNIT_OF_OPTIONAL_ITEM,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.USAGE_ATR, NULL) AS USAGE_ATR,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.PERFORMANCE_ATR, NULL) AS PERFORMANCE_ATR,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.EMP_CONDITION_ATR, NULL) AS EMP_CONDITION_ATR,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.NAME, NULL) AS NAME,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.UPPER_LIMIT_ATR, NULL) AS UPPER_LIMIT_ATR,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.UPPER_RANGE, NULL) AS UPPER_RANGE,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.LOWER_LIMIT_ATR, NULL) AS LOWER_LIMIT_ATR,");
	     exportSQL.append("    IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.LOWER_RANGE, NULL) AS LOWER_RANGE   ");
	     exportSQL.append("    ,RESULT_FINAL.SYMBOL");
	     exportSQL.append("    ,RESULT_FINAL.FORMULA_ATR");
	     exportSQL.append("    ,RESULT_FINAL.FORMULA_NAME");
	     exportSQL.append("    ,RESULT_FINAL.CALC_ATR");
	     exportSQL.append("    ,IIF(RESULT_FINAL.PERFORMANCE_ATR = 1, RESULT_FINAL.DAY_ROUNDING_UNIT, NULL) DAY_ROUNDING_UNIT");
	     exportSQL.append("    ,IIF(RESULT_FINAL.PERFORMANCE_ATR = 1, RESULT_FINAL.DAY_ROUNDING, NULL) DAY_ROUNDING");
	     exportSQL.append("    ,RESULT_FINAL.MON_ROUNDING_UNIT");
	     exportSQL.append("    ,RESULT_FINAL.MON_ROUNDING");
	     exportSQL.append("    ,RESULT_FINAL.CALC_ATR_2");
	     exportSQL.append("    ,RESULT_FINAL.ATTENDANCE_ITEM_NAME");
	     exportSQL.append("    ,RESULT_FINAL.ATTENDANCE_ITEM_2");
	     exportSQL.append("    , RESULT_FINAL.FORMULAR_FROM_FORMULAR");
	     exportSQL.append("    , RESULT_FINAL.FORMULAR");
	     exportSQL.append("    ,IIF(RESULT_FINAL.ROW_NUMBER = 1, RESULT_FINAL.NAME_OTHER, NULL) AS NAME_OTHERR");
	     exportSQL.append("   FROM");
	     exportSQL.append("    (SELECT RESULT_TOTAL.DISPORDER");
	     exportSQL.append("       ,RESULT_TOTAL.OPTIONAL_ITEM_NO");
	     exportSQL.append("       , RESULT_TOTAL.OPTIONAL_ITEM_NAME");
	     exportSQL.append("       ,RESULT_TOTAL.OPTIONAL_ITEM_ATR");
	     exportSQL.append("       ,RESULT_TOTAL.UNIT_OF_OPTIONAL_ITEM");
	     exportSQL.append("       ,RESULT_TOTAL.USAGE_ATR");
	     exportSQL.append("       ,RESULT_TOTAL.PERFORMANCE_ATR");
	     exportSQL.append("       ,RESULT_TOTAL.EMP_CONDITION_ATR");
	     exportSQL.append("       ,RESULT_TOTAL.NAME");
	     exportSQL.append("       ,RESULT_TOTAL.UPPER_LIMIT_ATR");
	     exportSQL.append("       ,RESULT_TOTAL.UPPER_RANGE");
	     exportSQL.append("       ,RESULT_TOTAL.LOWER_LIMIT_ATR");
	     exportSQL.append("       ,RESULT_TOTAL.LOWER_RANGE");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.SYMBOL, NULL) AS SYMBOL");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.FORMULA_ATR, NULL) AS FORMULA_ATR");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.FORMULA_NAME, NULL) AS FORMULA_NAME");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.CALC_ATR, NULL) AS CALC_ATR");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.DAY_ROUNDING_UNIT, NULL) AS DAY_ROUNDING_UNIT");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.DAY_ROUNDING, NULL) AS DAY_ROUNDING");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.MON_ROUNDING_UNIT, NULL) AS MON_ROUNDING_UNIT");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.MON_ROUNDING, NULL) AS MON_ROUNDING");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.CALC_ATR_2, NULL) AS CALC_ATR_2");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.ATTENDANCE_ITEM_NAME, NULL) AS ATTENDANCE_ITEM_NAME");
	     exportSQL.append("       ,IIF(RESULT_TOTAL.USAGE_ATR = 1, RESULT_TOTAL.ATTENDANCE_ITEM_2, NULL) AS ATTENDANCE_ITEM_2");
	     exportSQL.append("       , ROW_NUMBER() OVER (PARTITION BY RESULT_TOTAL.OPTIONAL_ITEM_NO ORDER BY RESULT_TOTAL.DISPORDER ASC, RESULT_TOTAL.OPTIONAL_ITEM_NO ASC) AS ROW_NUMBER");
	     exportSQL.append("       ,RESULT_TOTAL.FORMULAR_FROM_FORMULAR");
	     exportSQL.append("       ,RESULT_TOTAL.FORMULAR");
	     exportSQL.append("       ,RESULT_TOTAL.NAME_OTHER");
	     exportSQL.append("    FROM");
	     exportSQL.append("    (SELECT RESULT_LEFT.OPTIONAL_ITEM_NO");
	     exportSQL.append("     ,RESULT_LEFT.OPTIONAL_ITEM_NAME");
	     exportSQL.append("     ,RESULT_LEFT.NAME_OTHER");
	     exportSQL.append("     ,RESULT_LEFT.OPTIONAL_ITEM_ATR");
	     exportSQL.append("     ,RESULT_LEFT.UNIT_OF_OPTIONAL_ITEM");
	     exportSQL.append("     ,RESULT_LEFT.USAGE_ATR");
	     exportSQL.append("     ,RESULT_LEFT.PERFORMANCE_ATR");
	     exportSQL.append("     ,RESULT_LEFT.EMP_CONDITION_ATR");
	     exportSQL.append("     ,RESULT_LEFT.NAME");
	     exportSQL.append("     ,RESULT_RIGHT.UPPER_LIMIT_ATR");
	     exportSQL.append("     ,RESULT_RIGHT.UPPER_RANGE");
	     exportSQL.append("     ,RESULT_RIGHT.LOWER_LIMIT_ATR");
	     exportSQL.append("     ,RESULT_RIGHT.LOWER_RANGE");
	     exportSQL.append("     ,RESULT_RIGHT.SYMBOL");
	     exportSQL.append("     ,RESULT_RIGHT.FORMULA_ATR");
	     exportSQL.append("     ,RESULT_RIGHT.FORMULA_NAME");
	     exportSQL.append("     ,RESULT_RIGHT.CALC_ATR");
	     exportSQL.append("     ,RESULT_RIGHT.DAY_ROUNDING_UNIT");
	     exportSQL.append("     ,RESULT_RIGHT.DAY_ROUNDING");
	     exportSQL.append("     ,RESULT_RIGHT.MON_ROUNDING_UNIT");
	     exportSQL.append("     ,RESULT_RIGHT.MON_ROUNDING");
	     exportSQL.append("     ,RESULT_RIGHT.CALC_ATR_2");
	     exportSQL.append("     ,RESULT_RIGHT.ATTENDANCE_ITEM_NAME");
	     exportSQL.append("     ,RESULT_RIGHT.ATTENDANCE_ITEM_2");
	     exportSQL.append("     ,RESULT_RIGHT.DISPORDER");
	     exportSQL.append("      , RESULT_RIGHT.FORMULAR_FROM_FORMULAR");
	     exportSQL.append("      , RESULT_RIGHT.FORMULAR");
	     exportSQL.append("    FROM");
	     exportSQL.append("     (SELECT");
	     exportSQL.append("     RESULT_ONE.OPTIONAL_ITEM_NO");
	     exportSQL.append("     ,RESULT_ONE.OPTIONAL_ITEM_NAME");
	     exportSQL.append("     ,RESULT_ONE.OPTIONAL_ITEM_ATR");
	     exportSQL.append("     ,RESULT_ONE.UNIT_OF_OPTIONAL_ITEM");
	     exportSQL.append("     ,RESULT_ONE.USAGE_ATR");
	     exportSQL.append("     ,RESULT_ONE.PERFORMANCE_ATR");
	     exportSQL.append("     ,RESULT_ONE.EMP_CONDITION_ATR");
	     exportSQL.append("     ,RESULT_ONE.NAME");
	     exportSQL.append("     ,RESULT_ONE.NAME_OTHER");
	     exportSQL.append("      FROM (SELECT");
	     exportSQL.append("       oi.OPTIONAL_ITEM_NO");
	     exportSQL.append("      ,oi.OPTIONAL_ITEM_NAME");
	     exportSQL.append("      ,oi.OPTIONAL_ITEM_ATR");
	     exportSQL.append("      ,oi.UNIT_OF_OPTIONAL_ITEM");
	     exportSQL.append("      ,oi.USAGE_ATR");
	     exportSQL.append("      ,oi.PERFORMANCE_ATR");
	     exportSQL.append("      ,oi.EMP_CONDITION_ATR");
	     exportSQL.append("      ,IIF(oi.EMP_CONDITION_ATR = 1,STUFF((");
	     exportSQL.append("       SELECT");
	     exportSQL.append("      IIF(oi.EMP_CONDITION_ATR = 1,', ' + ec1.EMP_CD + (CASE WHEN emp1.NAME IS NULL THEN 'マスタ未登録' ELSE  emp1.NAME END), NULL)");
	     exportSQL.append("       FROM");
	     exportSQL.append("       KRCMT_ANYF_COND_EMP ec1");
	     exportSQL.append("       LEFT JOIN BSYMT_EMPLOYMENT emp1 ON ec1.CID = emp1.CID ");
	     exportSQL.append("       AND ec1.EMP_CD = emp1.CODE ");
	     exportSQL.append("    WHERE");
	     exportSQL.append("     oi.CID = ec1.CID AND ec1.EMP_APPL_ATR = 1 AND oi.OPTIONAL_ITEM_NO = ec1.OPTIONAL_ITEM_NO ORDER BY ec1.EMP_CD");
	     exportSQL.append("        FOR XML PATH ('')");
	     exportSQL.append("        ),");
	     exportSQL.append("       1,");
	     exportSQL.append("       1,");
	     exportSQL.append("       ''");
	     exportSQL.append("      ), NULL) AS NAME");
	     exportSQL.append("      , oth.OPTIONAL_ITEM_NAME as NAME_OTHER");
	     exportSQL.append("     FROM");
	     exportSQL.append("     KRCMT_ANYV oi");
	     exportSQL.append("     LEFT JOIN KRCST_OPT_ITEM_NAME_OTHER oth ON  oi.CID = oth.CID AND oi.OPTIONAL_ITEM_NO = oth.OPTIONAL_ITEM_NO AND LANG_ID = ?langId");
//	     exportSQL.append("     --LEFT JOIN KRCMT_ANYF_COND_EMP ec ON oi.OPTIONAL_ITEM_NO = ec.OPTIONAL_ITEM_NO");
//	     exportSQL.append("     --AND oi.CID = ec.CID");
//	     exportSQL.append("     --LEFT JOIN BSYMT_EMPLOYMENT emp ON ec.CID = emp.CID");
//	     exportSQL.append("     --AND ec.EMP_CD = emp.CODE");
	     exportSQL.append("    WHERE");
	     exportSQL.append("     oi.CID = ?companyId ");
	     exportSQL.append("   ) AS RESULT_ONE");
	     exportSQL.append("   GROUP BY");
	     exportSQL.append("     RESULT_ONE.OPTIONAL_ITEM_NO");
	     exportSQL.append("    ,RESULT_ONE.OPTIONAL_ITEM_NAME");
	     exportSQL.append("    ,RESULT_ONE.OPTIONAL_ITEM_ATR");
	     exportSQL.append("    ,RESULT_ONE.UNIT_OF_OPTIONAL_ITEM");
	     exportSQL.append("    ,RESULT_ONE.USAGE_ATR");
	     exportSQL.append("    ,RESULT_ONE.PERFORMANCE_ATR");
	     exportSQL.append("    ,RESULT_ONE.EMP_CONDITION_ATR");
	     exportSQL.append("    ,RESULT_ONE.NAME");
	     exportSQL.append("    ,RESULT_ONE.NAME_OTHER");
	     exportSQL.append("   ) RESULT_LEFT");
	     exportSQL.append("   LEFT JOIN");
	     exportSQL.append("   (SELECT * FROM");
	     exportSQL.append("   (");
	     exportSQL.append("    SELECT");
	     exportSQL.append("    oi.OPTIONAL_ITEM_NO");
	     exportSQL.append("    ,crr.UPPER_LIMIT_ATR");
	     exportSQL.append("    ,(CASE oi.OPTIONAL_ITEM_ATR");
	     exportSQL.append("      WHEN 0 THEN crr.UPPER_TIME_RANGE");
	     exportSQL.append("      WHEN 1 THEN crr.UPPER_NUMBER_RANGE");
	     exportSQL.append("      WHEN 2 THEN crr.UPPER_AMOUNT_RANGE");
	     exportSQL.append("     END) AS UPPER_RANGE");
	     exportSQL.append("     ,crr.LOWER_LIMIT_ATR");
	     exportSQL.append("     ,(CASE oi.OPTIONAL_ITEM_ATR");
	     exportSQL.append("      WHEN 0 THEN crr.LOWER_TIME_RANGE");
	     exportSQL.append("      WHEN 1 THEN crr.LOWER_NUMBER_RANGE");
	     exportSQL.append("      WHEN 2 THEN crr.LOWER_AMOUNT_RANGE");
	     exportSQL.append("      END) AS LOWER_RANGE");
	     exportSQL.append("     ,oif.SYMBOL");
	     exportSQL.append("    ,oif.FORMULA_ATR");
	     exportSQL.append("    ,oif.FORMULA_NAME");
	     exportSQL.append("    ,oif.CALC_ATR");
	     exportSQL.append("      ,(CASE oi.OPTIONAL_ITEM_ATR");
	     exportSQL.append("      WHEN 0 THEN fr_day.TIME_ROUNDING_UNIT");
	     exportSQL.append("      WHEN 1 THEN fr_day.NUMBER_ROUNDING_UNIT");
	     exportSQL.append("      WHEN 2 THEN fr_day.AMOUNT_ROUNDING_UNIT");
	     exportSQL.append("     END) AS DAY_ROUNDING_UNIT");
	     exportSQL.append("     ,(CASE oi.OPTIONAL_ITEM_ATR");
	     exportSQL.append("      WHEN 0 THEN fr_day.TIME_ROUNDING");
	     exportSQL.append("      WHEN 1 THEN fr_day.NUMBER_ROUNDING");
	     exportSQL.append("      WHEN 2 THEN fr_day.AMOUNT_ROUNDING");
	     exportSQL.append("      END) AS DAY_ROUNDING");
	     exportSQL.append("     ,(CASE oi.OPTIONAL_ITEM_ATR");
	     exportSQL.append("      WHEN 0 THEN fr_month.TIME_ROUNDING_UNIT");
	     exportSQL.append("      WHEN 1 THEN fr_month.NUMBER_ROUNDING_UNIT");
	     exportSQL.append("      WHEN 2 THEN fr_month.AMOUNT_ROUNDING_UNIT");
	     exportSQL.append("     END) AS MON_ROUNDING_UNIT");
	     exportSQL.append("     ,(CASE oi.OPTIONAL_ITEM_ATR");
	     exportSQL.append("      WHEN 0 THEN fr_month.TIME_ROUNDING");
	     exportSQL.append("      WHEN 1 THEN fr_month.NUMBER_ROUNDING");
	     exportSQL.append("      WHEN 2 THEN fr_month.AMOUNT_ROUNDING");
	     exportSQL.append("     END) AS MON_ROUNDING");
	     exportSQL.append("    ,oif.CALC_ATR AS CALC_ATR_2");
	     exportSQL.append("    ,fd.DISPORDER");
	     exportSQL.append("   , IIF(oif.CALC_ATR = 0 , IIF(oi.PERFORMANCE_ATR = 1, (STUFF((");
	     exportSQL.append("       SELECT ");
	     exportSQL.append("         ' '");
	     exportSQL.append("        + (");
	     exportSQL.append("            SELECT CASE B.FRAME_CATEGORY ");
	     exportSQL.append("       WHEN 0 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name1.OT_FR_NAME FROM KSHMT_OVER_FRAME name1 WHERE cis1.CID = name1.CID AND  name1.OT_FR_NO = B.FRAME_NO)))) ");
	     exportSQL.append("       WHEN 1 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name2.OT_FR_NAME FROM KSHMT_OVER_FRAME name2 WHERE cis1.CID = name2.CID AND  name2.OT_FR_NO = B.FRAME_NO))))   ");
	     exportSQL.append("       WHEN 2 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name3.WDO_FR_NAME FROM KSHMT_HD_WORK_FRAME name3 WHERE cis1.CID = name3.CID AND  name3.WDO_FR_NO = B.FRAME_NO))))");
	     exportSQL.append("       WHEN 3 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name4.TRANS_FR_NAME FROM KSHMT_HD_WORK_FRAME name4 WHERE cis1.CID = name4.CID AND  name4.WDO_FR_NO = B.FRAME_NO))))");
	     exportSQL.append("       WHEN 4 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name5.PREMIUM_NAME FROM KSCMT_PREMIUM_ITEM name5 WHERE cis1.CID = name5.CID AND  name5.PREMIUM_NO = B.FRAME_NO))))");
	     exportSQL.append("       WHEN 5 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name6.TIME_ITEM_NAME FROM KRCMT_BONUS_PAY_ITEM name6 WHERE cis1.CID = name6.CID AND  name6.TIME_ITEM_NO = B.FRAME_NO))))");
	     exportSQL.append("       WHEN 6 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name7.TIME_ITEM_NAME FROM KRCMT_BONUS_PAY_ITEM name7 WHERE cis1.CID = name7.CID AND  name7.TIME_ITEM_NO = B.FRAME_NO))))");
	     exportSQL.append("       WHEN 7 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name8.DVGC_TIME_NAME FROM KRCMT_DVGC_TIME name8 WHERE cis1.CID = name8.CID AND  name8.[NO] = B.FRAME_NO ))))");
	     exportSQL.append("       WHEN 8 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name9.OPTIONAL_ITEM_NAME FROM KRCMT_ANYV name9 WHERE cis1.CID = name9.CID AND  name9.OPTIONAL_ITEM_NO = B.FRAME_NO)), '{1}', (SELECT ISNULL(name91.UNIT_OF_OPTIONAL_ITEM,'') FROM KRCMT_ANYV name91 WHERE cis1.CID = name91.CID AND  name91.OPTIONAL_ITEM_NO = B.FRAME_NO))))");
	     exportSQL.append("       WHEN 10 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name11.NAME FROM KSCMT_SPEC_DATE_ITEM name11 WHERE cis1.CID = name11.CID AND  name11.SPECIFIC_DATE_ITEM_NO = B.FRAME_NO))))");
//	     exportSQL.append("       -- WHEN 11 THEN (REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name12.NAME FROM KSHMT_OUTSIDE name12 WHERE cis1.CID = name12.CID AND  name12.OVER_TIME_NO = B.FRAME_NO AND B.TYPE_OF_ITEM = 1)))");
	     exportSQL.append("       WHEN 11 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name12.NAME FROM KSHMT_OUTSIDE name12 WHERE cis1.CID = name12.CID AND  name12.OVER_TIME_NO = B.FRAME_NO)), '{1}', (SELECT ISNULL(ooba.NAME,'') FROM KSHMT_OUTSIDE_DETAIL ooba WHERE ooba.BRD_ITEM_NO = B.PRELIMINARY_FRAME_NO AND dai.CID = ooba.CID))))  ");
	     exportSQL.append("       WHEN 12 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name13.NAME FROM KSHMT_ABSENCE_FRAME name13 WHERE cis1.CID = name13.CID AND  name13.ABSENCE_FRAME_NO = B.FRAME_NO ))))");
	     exportSQL.append("       WHEN 13 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name14.NAME FROM KSHMT_HDSP_FRAME name14 WHERE cis1.CID = name14.CID AND  name14.SPHD_FRAME_NO = B.FRAME_NO ))))");
	     exportSQL.append("       WHEN 14 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name15.TOTAL_TIMES_NAME FROM KSHMT_TOTAL_TIMES name15 WHERE cis1.CID = name15.CID AND  name15.TOTAL_TIMES_NO = B.FRAME_NO )), '{1}', (SELECT ISNULL(name15.TOTAL_TIMES_ABNAME,'') FROM KSHMT_TOTAL_TIMES name15 WHERE cis.CID = name15.CID AND  name15.TOTAL_TIMES_NO = B.FRAME_NO))))");
	     exportSQL.append("       WHEN 15 THEN CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(dai.ATTENDANCE_ITEM_NAME, '{0}', (SELECT name16.SPHD_NAME FROM KSHMT_HDSP name16 WHERE cis1.CID = name16.CID AND  name16.SPHD_CD = B.FRAME_NO)), '{1}', (SELECT ISNULL(name16.MEMO,'') FROM KSHMT_HDSP name16 WHERE cis.CID = name16.CID AND  name16.SPHD_CD = B.FRAME_NO))))");
	     exportSQL.append("             ELSE  CONCAT(CASE cis1.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END, dai.ATTENDANCE_ITEM_NAME)");
	     exportSQL.append("             END ");
	     exportSQL.append("           )      ");
	     exportSQL.append("       FROM");
	     exportSQL.append("        KRCMT_ANYF_ITEM_SELECT cis1");
//	     exportSQL.append("        -- LEFT JOIN KRCMT_MON_ATTENDANCE_ITEM mai ON mai.CID = cis.CID AND mai.M_ATD_ITEM_ID = cis.ATTENDANCE_ITEM_ID AND cis.CID = ?companyId   ");
	     exportSQL.append("        LEFT JOIN KRCMT_DAY_ATTENDANCE_ITEM dai ON dai.CID = cis1.CID AND dai.ATTENDANCE_ITEM_ID = cis1.ATTENDANCE_ITEM_ID AND cis1.CID = ?companyId");
	     exportSQL.append("       LEFT JOIN KFNMT_ATTENDANCE_LINK B ON( ");
//	     exportSQL.append("       -- mai.M_ATD_ITEM_ID = B.ATTENDANCE_ITEM_ID OR ");
	     exportSQL.append("       dai.ATTENDANCE_ITEM_ID = B.ATTENDANCE_ITEM_ID AND B.TYPE_OF_ITEM = 1)");
	     exportSQL.append("       LEFT JOIN KRCMT_ANYF_SORT fd1 ON cis1.OPTIONAL_ITEM_NO = fd1.OPTIONAL_ITEM_NO AND cis1.CID = fd1.CID AND        cis1.FORMULA_ID = fd1.FORMULA_ID");
	     exportSQL.append("       WHERE");
	     exportSQL.append("        fr_day.FORMULA_ID = cis1.FORMULA_ID  AND cis1.OPTIONAL_ITEM_NO = cis.OPTIONAL_ITEM_NO AND cis1.CID = cis.CID");
	     exportSQL.append("       ORDER BY");
	     exportSQL.append("        fd1.DISPORDER,dai.DISPLAY_NUMBER FOR XML PATH ('')");
	     exportSQL.append("        ),");
	     exportSQL.append("       1,");
	     exportSQL.append("       1,");
	     exportSQL.append("       ''");
	     exportSQL.append("      )), (STUFF((");
	     exportSQL.append("       SELECT ");
	     exportSQL.append("         ' ' ");
	     exportSQL.append("        + (");
	     exportSQL.append("            SELECT CASE B1.FRAME_CATEGORY ");
	     exportSQL.append("             WHEN 0 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name1.OT_FR_NAME FROM KSHMT_OVER_FRAME name1 WHERE cis.CID = name1.CID AND  name1.OT_FR_NO = B1.FRAME_NO )))) ");
	     exportSQL.append("       WHEN 1 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name2.OT_FR_NAME FROM KSHMT_OVER_FRAME name2 WHERE cis2.CID = name2.CID AND  name2.OT_FR_NO = B1.FRAME_NO ))))   ");
	     exportSQL.append("       WHEN 2 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name3.WDO_FR_NAME FROM KSHMT_HD_WORK_FRAME name3 WHERE cis2.CID = name3.CID AND  name3.WDO_FR_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 3 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name4.TRANS_FR_NAME FROM KSHMT_HD_WORK_FRAME name4 WHERE cis2.CID = name4.CID AND  name4.WDO_FR_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 4 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name5.PREMIUM_NAME FROM KSCMT_PREMIUM_ITEM name5 WHERE cis2.CID = name5.CID AND  name5.PREMIUM_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 5 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name6.TIME_ITEM_NAME FROM KRCMT_BONUS_PAY_ITEM name6 WHERE cis2.CID = name6.CID AND  name6.TIME_ITEM_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 6 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name7.TIME_ITEM_NAME FROM KRCMT_BONUS_PAY_ITEM name7 WHERE cis2.CID = name7.CID AND  name7.TIME_ITEM_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 7 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name8.DVGC_TIME_NAME FROM KRCMT_DVGC_TIME name8 WHERE cis2.CID = name8.CID AND  name8.[NO] = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 8 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(mai.M_ATD_ITEM_NAME, '{0}',(SELECT name9.OPTIONAL_ITEM_NAME FROM KRCMT_ANYV name9 WHERE cis2.CID = name9.CID AND  name9.OPTIONAL_ITEM_NO = B1.FRAME_NO )), '{1}', (SELECT ISNULL(name9.UNIT_OF_OPTIONAL_ITEM,'') FROM KRCMT_ANYV name9 WHERE cis2.CID = name9.CID AND  name9.OPTIONAL_ITEM_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 10 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name11.NAME FROM KSCMT_SPEC_DATE_ITEM name11 WHERE cis2.CID = name11.CID AND  name11.SPECIFIC_DATE_ITEM_NO = B1.FRAME_NO ))))");
//	     exportSQL.append("       -- WHEN 11 THEN (REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name12.NAME FROM KSHMT_OUTSIDE name12 WHERE cis.CID = name12.CID AND  name12.OVER_TIME_NO = B.FRAME_NO AND B.TYPE_OF_ITEM = 2)))");
	     exportSQL.append("        WHEN 11 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT  name12.NAME FROM KSHMT_OUTSIDE name12 WHERE cis2.CID = name12.CID AND  name12.OVER_TIME_NO = B1.FRAME_NO )), '{1}', (SELECT ISNULL(ooba.NAME,'') FROM KSHMT_OUTSIDE_DETAIL ooba WHERE ooba.BRD_ITEM_NO = B1.PRELIMINARY_FRAME_NO AND mai.CID = ooba.CID ))))");
	     exportSQL.append("       WHEN 12 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name13.NAME FROM KSHMT_ABSENCE_FRAME name13 WHERE cis2.CID = name13.CID AND  name13.ABSENCE_FRAME_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 13 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name14.NAME FROM KSHMT_HDSP_FRAME name14 WHERE cis2.CID = name14.CID AND  name14.SPHD_FRAME_NO = B1.FRAME_NO ))))");
	     exportSQL.append("       WHEN 14 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name15.TOTAL_TIMES_NAME FROM KSHMT_TOTAL_TIMES name15 WHERE cis2.CID = name15.CID AND  name15.TOTAL_TIMES_NO = B1.FRAME_NO )), '{1}', (SELECT ISNULL(name15.TOTAL_TIMES_ABNAME,'') FROM KSHMT_TOTAL_TIMES name15 WHERE cis2.CID = name15.CID AND  name15.TOTAL_TIMES_NO = B1.FRAME_NO ))))           ");
	     exportSQL.append("       WHEN 15 THEN CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END,(REPLACE(REPLACE(mai.M_ATD_ITEM_NAME, '{0}', (SELECT name16.SPHD_NAME FROM KSHMT_HDSP name16 WHERE cis2.CID = name16.CID AND  name16.SPHD_CD = B1.FRAME_NO )), '{1}', (SELECT ISNULL(name16.MEMO,'') FROM KSHMT_HDSP name16 WHERE cis2.CID = name16.CID AND  name16.SPHD_CD = B1.FRAME_NO ))))");
	     exportSQL.append("             ELSE CONCAT(CASE cis2.OPERATOR  WHEN 0 THEN '+ ' WHEN 1 THEN '- ' WHEN 2 THEN '* ' WHEN 3 THEN '/ ' END, mai.M_ATD_ITEM_NAME)");
	     exportSQL.append("             END ");
	     exportSQL.append("           )       ");
	     exportSQL.append("       FROM");
	     exportSQL.append("        KRCMT_ANYF_ITEM_SELECT cis2");
	     exportSQL.append("        LEFT JOIN KRCMT_MON_ATTENDANCE_ITEM mai ON mai.CID = cis2.CID AND mai.M_ATD_ITEM_ID = cis2.ATTENDANCE_ITEM_ID AND cis2.CID = ?companyId   ");
//	     exportSQL.append("        -- LEFT JOIN KRCMT_DAY_ATTENDANCE_ITEM dai ON dai.CID = cis.CID AND dai.ATTENDANCE_ITEM_ID = cis.ATTENDANCE_ITEM_ID AND cis.CID = ?companyId");
	     exportSQL.append("       LEFT JOIN KFNMT_ATTENDANCE_LINK B1 ON( mai.M_ATD_ITEM_ID = B1.ATTENDANCE_ITEM_ID ");
	     exportSQL.append("       AND B1.TYPE_OF_ITEM = 2");
//	     exportSQL.append("       -- OR dai.ATTENDANCE_ITEM_ID = B.ATTENDANCE_ITEM_ID");
	     exportSQL.append("       )");
	     exportSQL.append("       LEFT JOIN KRCMT_ANYF_SORT fd2 ON cis2.OPTIONAL_ITEM_NO = fd2.OPTIONAL_ITEM_NO AND cis2.CID = fd2.CID AND        cis2.FORMULA_ID = fd2.FORMULA_ID");
	     exportSQL.append("       WHERE");
	     exportSQL.append("        fr_month.FORMULA_ID = cis2.FORMULA_ID  AND cis2.OPTIONAL_ITEM_NO = cis.OPTIONAL_ITEM_NO");
	     exportSQL.append("       ORDER BY");
	     exportSQL.append("        fd2.DISPORDER, mai.DISP_NO FOR XML PATH ('')");
	     exportSQL.append("        ),");
	     exportSQL.append("       1,");
	     exportSQL.append("       1,");
	     exportSQL.append("       ''");
	     exportSQL.append("      ))) , NULL) AS ATTENDANCE_ITEM_NAME");
	     exportSQL.append("   ,");
	     exportSQL.append("   IIF(oif.CALC_ATR = 1 ,");
	     exportSQL.append("   (CASE fs.LEFT_SET_METHOD ");
	     exportSQL.append("  WHEN 1 THEN");
	     exportSQL.append("  CONVERT ( VARCHAR, fs.LEFT_INPUT_VAL )");
	     exportSQL.append("  WHEN 0 THEN");
	     exportSQL.append("   CONVERT (VARCHAR,");
	     exportSQL.append("   ( SELECT koiff.SYMBOL FROM KRCMT_ANYF koiff WHERE koiff.OPTIONAL_ITEM_NO = oi.OPTIONAL_ITEM_NO AND fs.LEFT_FORMULA_ITEM_ID = koiff.FORMULA_ID)) ");
	     exportSQL.append(" END)");
	     exportSQL.append(" +");
	     exportSQL.append(" CASE");
	     exportSQL.append("    fs.OPERATOR ");
	     exportSQL.append("   WHEN 0 THEN");
	     exportSQL.append("   ' + ' ");
	     exportSQL.append("   WHEN 1 THEN");
	     exportSQL.append("   ' - ' ");
	     exportSQL.append("   WHEN 2 THEN");
	     exportSQL.append("   ' * ' ");
	     exportSQL.append("   WHEN 3 THEN");
	     exportSQL.append("   ' / ' ");
	     exportSQL.append("  END ");
	     exportSQL.append(" +");
	     exportSQL.append(" (CASE fs.RIGHT_SET_METHOD ");
	     exportSQL.append("  WHEN 1 THEN");
	     exportSQL.append("  CONVERT ( VARCHAR, fs.RIGHT_INPUT_VAL )");
	     exportSQL.append("  WHEN 0 THEN");
	     exportSQL.append("   CONVERT (VARCHAR,");
	     exportSQL.append("   ( SELECT koiff.SYMBOL FROM KRCMT_ANYF koiff WHERE koiff.OPTIONAL_ITEM_NO = oi.OPTIONAL_ITEM_NO AND fs.RIGHT_FORMULA_ITEM_ID = koiff.FORMULA_ID)) ");
	     exportSQL.append(" END)");
	     exportSQL.append("    , NULL) AS ATTENDANCE_ITEM_2,");
	     exportSQL.append("      fs.MINUS_SEGMENT as  FORMULAR_FROM_FORMULAR,");
	     exportSQL.append("      cis.MINUS_SEGMENT as FORMULAR");
	     exportSQL.append("   FROM");
	     exportSQL.append("    KRCMT_ANYV oi");
	     exportSQL.append("    LEFT JOIN KRCMT_ANYF_RESULT_RANGE crr ON oi.CID = crr.CID AND oi.OPTIONAL_ITEM_NO = crr.OPTIONAL_ITEM_NO");
	     exportSQL.append("    LEFT JOIN KRCMT_ANYF_ROUND fr_day ON oi.CID = fr_day.CID AND oi.OPTIONAL_ITEM_NO = fr_day.OPTIONAL_ITEM_NO AND fr_day.ROUNDING_ATR = 1");
//	     exportSQL.append("    -- list formula");
	     exportSQL.append("    LEFT JOIN KRCMT_ANYF_ROUND fr_month ON oi.CID = fr_month.CID AND oi.OPTIONAL_ITEM_NO = fr_month.OPTIONAL_ITEM_NO AND fr_month.ROUNDING_ATR = 2 AND fr_day.FORMULA_ID = fr_month.FORMULA_ID");
//	     exportSQL.append("    -- name formula");
	     exportSQL.append("    LEFT JOIN KRCMT_ANYF oif ON oi.CID = oif.CID AND oi.OPTIONAL_ITEM_NO = oif.OPTIONAL_ITEM_NO AND fr_day.FORMULA_ID = oif.FORMULA_ID");
	     exportSQL.append("    LEFT JOIN KRCMT_ANYF_SORT fd ON oif.OPTIONAL_ITEM_NO = fd.OPTIONAL_ITEM_NO AND oif.CID = fd.CID AND oif.FORMULA_ID = fd.FORMULA_ID");
	     exportSQL.append("    LEFT JOIN KRCMT_ANYF_ITEM_SELECT cis ON fd.FORMULA_ID = cis.FORMULA_ID AND fd.OPTIONAL_ITEM_NO = cis.OPTIONAL_ITEM_NO AND cis.CID = fd.CID");
	     exportSQL.append("    LEFT JOIN KRCMT_ANYF_DETAIL fs ON fd.FORMULA_ID = fs.FORMULA_ID  AND fd.OPTIONAL_ITEM_NO = fs.OPTIONAL_ITEM_NO");
	     exportSQL.append("   WHERE");
	     exportSQL.append("    oi.CID = ?companyId ");
	     exportSQL.append("    ) AS RESULT_END");
	     exportSQL.append("   GROUP BY OPTIONAL_ITEM_NO, SYMBOL, FORMULA_ATR, FORMULA_NAME, CALC_ATR, ATTENDANCE_ITEM_NAME, ATTENDANCE_ITEM_2, UPPER_LIMIT_ATR, UPPER_RANGE, LOWER_LIMIT_ATR, LOWER_RANGE, DAY_ROUNDING_UNIT, DAY_ROUNDING, MON_ROUNDING_UNIT, MON_ROUNDING, UPPER_LIMIT_ATR, CALC_ATR_2, DISPORDER,FORMULAR_FROM_FORMULAR,FORMULAR) AS RESULT_RIGHT");
	     exportSQL.append("   ON RESULT_LEFT.OPTIONAL_ITEM_NO = RESULT_RIGHT.OPTIONAL_ITEM_NO ) AS RESULT_TOTAL");
	     exportSQL.append("   )AS RESULT_FINAL  ORDER BY RESULT_FINAL.OPTIONAL_ITEM_NO ASC");

	     GET_EXPORT_EXCEL_LANG = exportSQL.toString();
	  }
}
